theme: jekyll-theme-cayman
description: "Workshop on"
title: "Informed Scientific Sampling in Large-scale Outdoor Environments"
description: "IROS 2019 Macau"
github:
  is_project_page: false
kramdown:
    auto_ids: true
